In [ ]:
# NUMPY: NUMERIC PYTHON IS A MODULE FOR PYTHON
# IS KNOWN AS GENERAL PURPOSE ARRAY PROCESSING PACKAGE.

In [ ]:
!pip install numpy

In [1]:
#CREATION OF ARRAY
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
print('array :',arr)

array : [1 2 3]


In [3]:
arr= np.array([[1,2,3],
              [4,5,6]])
print('array 2:',arr)

array 2: [[1 2 3]
 [4 5 6]]


In [4]:
#create array from tuple
#import numpy as np
arr= np.array((1,2,3))
print('array with tuples', arr)
print(arr.dtype)

array with tuples [1 2 3]
int32


In [53]:
#to check order of matrix

arr= np.array([[1, 2, 3, 4],[2, 3,4],[4,5,6]]) #order of matrix
arr.shape

(3,)

In [9]:
arr=np.array([[1,2,3],[5,6,9]])
arr.shape #has 3 elements in 2 arrays

(2, 3)

In [ ]:
#DATA TYPES IN NUMPY
#HOW TO CONSTRUCT DATATYPE 
# WE DONT NEED TO DEFINE A DATATYPE. NUMPY TRIES TO GUESS THE DATATYPE FOR ARRAYS.

In [10]:
#INT DATATYPE 
a= np.array([1,2])
print('int datatype:')
print(a.dtype) #GUESSED BY NUMPY

int datatype:
int32


In [11]:
#FLOAT DTYPE
arr= np.array([2.5,9.5])
print('float dtype:')
arr.dtype

float dtype:


dtype('float64')

In [12]:
#FORCING A DTYPE  ON NUMPY
a= np.array([5,9], dtype = np.int64) 
print('forcing a dtype:')
print(a.dtype)

forcing a dtype:
int64


In [13]:
a = [1, 2, 3]
type(a)

list

In [14]:
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
print(type(a))

<class 'list'>


In [17]:
#PERFORMING MATH OPERATIONS OF DTYPE ARRAY
a1 = np.array([[1,2],[3,4]], dtype = np.int32)
a2 = np.array([[8,4],[9,4]], dtype = np.float64)
#addition 
sum= np.add(a1,a2)
print(sum)

[[ 9.  6.]
 [12.  8.]]


In [54]:
#SQUARE ROOT OF ARRAY
a3=np.array([100,3])
sqrt = np.sqrt(a3)
print(sqrt)

[10.          1.73205081]


In [19]:
#TRANSPOSE OF AN ARRAY
#a1 = np.array([[1,2],[3,4]], dtype = np.int32)
transpose= a1.T # we use in_built function T
print(transpose)

[[1 3]
 [2 4]]


In [55]:
lst_1 = [*range(100)]
print(lst_1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [21]:
lst_1 = [i for i in range(10)]
print(lst_1) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#conda update ipython

In [22]:
#LIST OF square of NUMBERS 
%time
sqr=[]
for x in range(10):
    sqr.append(x*x)
print(sqr)

Wall time: 0 ns
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [23]:
#COMPREHNSION FOR ABOVE

sqr= [x*x for x in range(10)]
print(sqr)

Wall time: 0 ns
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [24]:
x=np.arange(21) # returs the range of an given array
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [31]:
#RESHAPE : IT IS WHEN YOU CHANGE NUMBER OF ROWS AND COLUMNS WHICH GIVES NEW VIEW TO THE OBJECT

import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
a= a.reshape(3,2)
print('\nafter reshape\n',a)

[[ 8  9 10]
 [11 12 13]]

after reshape
 [[ 8  9]
 [10 11]
 [12 13]]


In [ ]:
#Performance Measurement
#THIS IS PROCESS OF COLLECTING AND UNDERSTANDING INFORMATION REGARDING THE PERFORMANCE OF CODE


In [ ]:
#using numpy can save a lot of time when compared to standard python lists.

In [32]:
#TIMEIT : used to measure the time of execution of a code snippet
x= range(2000)
%timeit [i*2 for i in x ]

353 µs ± 35.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [33]:
c_numpy = np.arange(20000)
%timeit c_numpy*2

33.2 µs ± 480 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
#CREATING NUMPY ARRAY USING ARANGE KEYWORD
array= np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
array = np.arange(5,10)
print(array)

[5 6 7 8 9]


In [36]:
array = np.arange(1,10,2)
print(array)

[1 3 5 7 9]


In [56]:
#ZERO AND ONE FUNCTION to create an array  filled with zeros and one.
a = np.zeros((2,6))      #dtype= np.int32)
print(a)   

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [40]:
b= np.ones((1,2))
print(b)

[[1. 1.]]


In [46]:
c= np.full((2,2),100)# CREATES AN ARRAY FILLED WITH THE GIVEN VALUE
print(c)

[[100 100]
 [100 100]]


In [47]:
#EYE FUNCTION: LETS YOU AN IDENTITY MATRIX
d=np.eye (4,4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
#DIAG : LETS YOU FILL DIAGONAL WITH YOUR CHOICE OF ELEMENTS
A= np.diag([5,10,15,20])
print(A)

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]


In [49]:
B= np.diag(['a','d',1,10])
print(B)

[['a' '' '' '']
 ['' 'd' '' '']
 ['' '' '1' '']
 ['' '' '' '10']]


In [50]:
c= np.diag(np.arange(1,50))
print(c)


[[ 1  0  0 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 [ 0  0  3 ...  0  0  0]
 ...
 [ 0  0  0 ... 47  0  0]
 [ 0  0  0 ...  0 48  0]
 [ 0  0  0 ...  0  0 49]]


In [53]:
#TILE : TILES UP EACH ROW AND COL OR STACKS COPIES OF THE VECTOR 
x= np.array([[2,4,6],[1,3,5]])
print(x)
np.tile(x,(3,2))

[[2 4 6]
 [1 3 5]]


array([[2, 4, 6, 2, 4, 6],
       [1, 3, 5, 1, 3, 5],
       [2, 4, 6, 2, 4, 6],
       [1, 3, 5, 1, 3, 5],
       [2, 4, 6, 2, 4, 6],
       [1, 3, 5, 1, 3, 5]])

In [61]:
#NP.RANDOM.SEED FUNCTION PROVIDES AN INPUT FOR THE PSEUDO RANDOM NUMBER GENERATOR IN PYTHON
#WE SHOULD PROVIDE A SEED VALUE TO RANDOM GENERATOR
#SEED: MAPS PARTICULAR RANDOM NUMBER WITH MENTIONED SEED ARGUMENT
np.random.seed()
print(np.random.random())
'''print(np.random.random())
print(np.random.random())
print(np.random.random())'''

0.862555763234226


'print(np.random.random())\nprint(np.random.random())\nprint(np.random.random())'

In [74]:
#RANDOM(): THIS NUMBER IS USED TO GENERATE A FLOAT RANDOM NUMBER LESS THAN 1 AND GREATOR THAN OR EQUAL TO 0.

print('a random number between 0 and 1 is:', end='')
print(np.random.random())

a random number between 0 and 1 is:0.2028234396838131


In [111]:
arr= np.random.rand(2,2,1)
print('random no. is:',arr)


random no. is: [[[0.66829182]
  [0.30209369]]

 [[0.06760944]
  [0.9326165 ]]]


In [91]:
#random.rand: array of defined shape, filled with random
arr= np.random.rand(2,3)
print('arr filled with random val.',arr)

arr filled with random val. [[0.21675563 0.29339387 0.88025735]
 [0.83363806 0.52894885 0.02346   ]]


In [104]:
a= np.random.random((2,3))# array of random floats in interval of(0.0,1.0)
print(a) #2D array 

[[0.01363009 0.68182669 0.57394646]
 [0.31429765 0.85802292 0.61688016]]


In [105]:
#Round function: rounds off the given number and returns floating point number, if not no. of digits is provided
#it rounds off the number tp nearest interger
#a= np.random.random((2,3))
R= np.round(a,3)
print(R)

[[0.014 0.682 0.574]
 [0.314 0.858 0.617]]


In [115]:
arr= [1.3,3.4,4.2,6.8,19.5]
arr=np.round(arr)
print(arr)
arr.dtype

[ 1.  3.  4.  7. 20.]


dtype('float64')

In [4]:
#slice
a= np.array([[1,2,3,4],[6,7,8,10]])
slicee= a[1:]

print(slicee)

[[ 6  7  8 10]]


In [7]:
'''slicee= a[1::-1]
print(slicee)'''

[[ 6  7  8 10]
 [ 1  2  3  4]]


In [23]:
a= np.array([1,2,3,4,5,6,7,8,10])
slicee= a[np.array([0,5,-3])]
print(slicee)

[1 6 7]


In [21]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
x=a
x

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [25]:
x[8]=20 #replace  
x

array([ 1,  2,  3,  4,  5,  6,  7,  8, 20])

In [26]:
a #a also changes as x=a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 20])

In [27]:
np.shares_memory(a,x) #returns boolean value(if yes= true if not false)

True

In [ ]:
s=np.arange(10)
s

In [29]:
a= np.arange(1,5)
a

array([1, 2, 3, 4])

In [28]:
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.91294525])

In [30]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [31]:
np.sum(a)

10

In [32]:
a=np.array([[1,2],[5,6]])

a

array([[1, 2],
       [5, 6]])

In [33]:
x= a.sum(axis=0)
x

array([6, 8])

In [34]:
x=a.sum(axis=1)
x

array([ 3, 11])

In [35]:
a.max()
#prints maximum element

6

In [36]:
a.min()
#prints minimum element 

1

In [37]:
a.argmax()
#prints maximum index

3

In [38]:
a.argmin()
#prints min index

0

In [39]:
np.median(a)

3.5

In [40]:
np.mean(a)

3.5

In [41]:
np.std(a) #std deviation

2.0615528128088303

In [43]:
u = np.array([1,1,0], dtype = bool)
v = np.array([1,0,1], dtype = bool)


In [44]:
np.logical_or(u,v)

array([ True,  True,  True])

In [45]:
np.logical_and(u,v)

array([ True, False, False])

In [46]:
np.all(u == u)

True

In [47]:
a= np.array([6,1,9,3,8])
a

array([6, 1, 9, 3, 8])

In [48]:
np.sort(a)

array([1, 3, 6, 8, 9])

In [49]:
b=np.array([1,3,2,7])
np.argsort(b)#sorts according to the indices of original array elements

array([0, 2, 1, 3], dtype=int64)