#PANDAS IS AN OPENSOURCE LIBRARY THAT ALLOWS YPU TO PERFORM DATA MANIPULATION IN PYTHON.
#PANDAS PROVIDE AN EASY WAY  TO CREATE, MANIPULATE AND WRANGLE THE DATA.
ANALYSIS OF THE DATA CAN BE DONE IN 2 WAYS HERE
1) SERIES
2) DATAFRAMES


In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
#SERIES IS ONE DIMENSIONAL ARRAY. IT CAN HAVE ANY DATA TYPE LIKE int, float, string.

#CREATING SERIES
data= [1,2,3,4]
a= pd.Series(data)
a                    #displays default index

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
type(a)

pandas.core.series.Series

In [6]:
Index =['a','b','c','d']
b= pd.Series(data,Index)
b                        #users choice of index

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
c=pd.Series([5],['x'])
c                       #predefined index given by user

x    5
dtype: int64

In [8]:
#data that contains dictionary
d1= {'x':2,'y':4,'z':8}
sd=pd.Series(d1)
sd


x    2
y    4
z    8
dtype: int64

In [9]:
#data that has Ndarray
data= [[2,1,3],[4,5,6]]#2Darray
d= pd.Series(data)
d

0    [2, 1, 3]
1    [4, 5, 6]
dtype: object

In [10]:
#DATAFRAMES : we can convert numpy arr to panda df with pd.df()
#            dataframes are 2D arrays

a=pd.DataFrame(data)      #NUMPY to PANDAS
a

0  1  2
0  2  1  3
1  4  5  6

In [11]:
#pandas to Numpy
b=np.array(data)
b

array([[2, 1, 3],
       [4, 5, 6]])

In [12]:
print("dataframe:\n", a)
print("\nnumpy arr:\n",b)

dataframe:
    0  1  2
0  2  1  3
1  4  5  6

numpy arr:
 [[2 1 3]
 [4 5 6]]


In [13]:
#df as dict
d1= {'x':10,'y':20,'z':50}
d2= {'x':4,'y':8}
data = {'First':d1, 'second': d2}
df= pd.DataFrame(data)
df                                  #NAN : NULL OR MISSING VALUES

First  second
x     10     4.0
y     20     8.0
z     50     NaN

In [14]:
D1={'name':['lily', 'shru'], 'branch':['CSE', 'Arch']}
d1= pd.DataFrame(D1)
d1

name branch
0  lily    CSE
1  shru   Arch

In [15]:
#data as series
a1 = pd.Series([2,4,6,8])
a2 = pd.Series([1,3,5,7])
a3 = pd.Series(['x','y','z'])
d1 = {'even':a1,'odd':a2, 'var':a3}
df = pd.DataFrame(d1)
df

even  odd  var
0     2    1    x
1     4    3    y
2     6    5    z
3     8    7  NaN

In [16]:
#range data
#pd.date_range(date, period, frequency)
x = pd.date_range(start = '31-05-2019', end = '10-12-2019')

In [17]:
x

DatetimeIndex(['2019-05-31', '2019-06-01', '2019-06-02', '2019-06-03',
               '2019-06-04', '2019-06-05', '2019-06-06', '2019-06-07',
               '2019-06-08', '2019-06-09',
               ...
               '2019-10-03', '2019-10-04', '2019-10-05', '2019-10-06',
               '2019-10-07', '2019-10-08', '2019-10-09', '2019-10-10',
               '2019-10-11', '2019-10-12'],
              dtype='datetime64[ns]', length=135, freq='D')

In [18]:
#COLUMN SELECTION : TO SELECT A COLUMN, WE CAN EITHER ACCESS THE COLUMNS BY CALLING THEM BY THEIR COLUMN NAME.
data ={'NAME':['shruti','hemanka','akshaya','shriya'],
       'AGE':[23,21,24,16], 
       'QUAL.':['B.E','Msc','Mca','Mba'],
       'ADDRESS':['Belgaum','Delhi','Kerala','Blore']}
df= pd.DataFrame(data)
print(df[['NAME', 'ADDRESS']])

      NAME  ADDRESS
0   shruti  Belgaum
1  hemanka    Delhi
2  akshaya   Kerala
3   shriya    Blore


In [19]:
print(df)

      NAME  AGE QUAL.  ADDRESS
0   shruti   23   B.E  Belgaum
1  hemanka   21   Msc    Delhi
2  akshaya   24   Mca   Kerala
3   shriya   16   Mba    Blore


In [20]:
#COLUMN ADDITION
D={'one':pd.Series([10,12,13])}
df= pd.DataFrame(D)
print('before adding:\n',df)

before adding:
    one
0   10
1   12
2   13


In [21]:
#ADD NEW COL.
print("\nadding a new column by passing as series: ")
df['two']=pd.Series([2,4,8])

print(df)




adding a new column by passing as series: 
   one  two
0   10    2
1   12    4
2   13    8


In [35]:
#performing addition operation for col. of existing database

print('\nAdding the col. elements of existing columns in df:')
df['three']= df['one'] + df['two']
print (df)


Adding the col. elements of existing columns in df:
   one  two  three
0   10    2     12
1   12    4     16
2   13    8     21


In [36]:
#performing subtraction on the elemnets of existing df col.
print('\nAdding the col. elements of existing columns in df:')
df['three']= df['one'] - df['two']
print (df)


Adding the col. elements of existing columns in df:
   one  two  three
0   10    2      8
1   12    4      8
2   13    8      5


In [37]:
#column deletion Using Del. function
print('\nDeleting the third column using del:')
del df['three']
print (df)


Deleting the third column using del:
   one  two
0   10    2
1   12    4
2   13    8


In [38]:
#WE CAN ALSO USE POP()function:
print('\nDeleting the first col. using pop:')
df.pop('one')
print(df)


Deleting the first col. using pop:
   two
0    2
1    4
2    8


In [8]:
emp_id=[10,11,12,13,14,15,16,17,18,19,20]
fname=['shruti','abhi','akshaya','hemanka','jon','sourabh','amey','sanjana','archana','kriti']
lname=['deshpande','ND','M.','S.','Winston','snow','Diana','Latkr','smith','patil']
b_date=['12 dec','13 july','18 may','16 jan','14 june','03 feb','09 march','31 oct','2 nov','30 oct']
salary=[70000,50000,45000,50000,45000,75000,9500,5463,43524,55567]
    



In [9]:
data={'fname': fname,'lname':lname, 'b_date':b_date,'salaray': salary}
df=pd.DataFrame(data)
print(df)

     fname      lname    b_date  salaray
0   shruti  deshpande    12 dec    70000
1     abhi         ND   13 july    50000
2  akshaya         M.    18 may    45000
3  hemanka         S.    16 jan    50000
4      jon    Winston   14 june    45000
5  sourabh       snow    03 feb    75000
6     amey      Diana  09 march     9500
7  sanjana      Latkr    31 oct     5463
8  archana      smith     2 nov    43524
9    kriti      patil    30 oct    55567


In [15]:
#accessing elements
print(df.loc[6])

fname          amey
lname         Diana
b_date     09 march
salaray        9500
Name: 6, dtype: object


In [18]:
print(df.loc[4::-1])

   EMP_ID    FNAME      LNAME   B_DATE  SALARY
4      14      jon    Winston  14 june   45000
3      13  hemanka         S.   16 jan   50000
2      12  akshaya         M.   18 may   45000
1      11     abhi         ND  13 july   50000
0      10   shruti  deshpande   12 dec   30000


In [7]:
print( df.loc[6 : 10]) #specify the index 

    EMP_ID    FNAME    LNAME    B_DATE  SALARY
6       16     amey    Diana  09 march    9500
7       17  sanjana    Latkr    31 oct   15463
8       18  archana    smith     2 nov   43524
9       19    kriti    patil    30 oct   55567
10      20    smith  english   18 sept    1674


In [24]:
#SELECT ROWS BY INTEGER LOCATION
print (df.iloc[9])

EMP_ID        19
FNAME      kriti
LNAME      patil
B_DATE    30 oct
SALARY     55567
Name: 9, dtype: object


In [21]:
#it returns an array of specified shape and fills it with random integers from low to high
np.random.randint(low=10, high=100, size=10)
#low: lowest integer
#high: highest integer
#size: array size OR shape of output


array([13, 54, 20, 46, 62, 41, 77, 33, 87, 85])

In [22]:
np.random.choice([1, 2, 3, 4, 5, 6], 5)   #generates random samples

array([6, 4, 5, 1, 4])

In [35]:
temp = np.random.randint(low = 10, high =100, size = [20])
name = np.random.choice(['shruti', ' hemanka', 'akshaya', 'pink','blue'], 20)
random = np.random.choice([10,11,13,12,14], 20)

In [33]:
temp

array([90, 28, 65, 40, 24, 31, 30, 53, 42, 92, 57, 24, 98, 50, 99, 40, 96,
       92, 56, 70])

In [36]:
name

array(['akshaya', 'akshaya', 'blue', 'pink', 'pink', 'akshaya',
       ' hemanka', 'blue', 'blue', ' hemanka', 'blue', 'blue', ' hemanka',
       'akshaya', 'pink', 'shruti', 'blue', 'akshaya', ' hemanka', 'pink'],
      dtype='<U8')

In [37]:
random

array([10, 13, 13, 13, 14, 10, 11, 11, 11, 14, 12, 13, 13, 10, 13, 13, 10,
       14, 12, 12])

In [38]:
x=list(zip(temp,name,random)) #zips all the contents together
x

[(68, 'akshaya', 10),
 (82, 'akshaya', 13),
 (58, 'blue', 13),
 (45, 'pink', 13),
 (49, 'pink', 14),
 (12, 'akshaya', 10),
 (53, ' hemanka', 11),
 (78, 'blue', 11),
 (98, 'blue', 11),
 (30, ' hemanka', 14),
 (22, 'blue', 12),
 (37, 'blue', 13),
 (20, ' hemanka', 13),
 (20, 'akshaya', 10),
 (44, 'pink', 13),
 (72, 'shruti', 13),
 (53, 'blue', 10),
 (95, 'akshaya', 14),
 (49, ' hemanka', 12),
 (66, 'pink', 12)]

In [39]:
df = pd.DataFrame(data = x, columns=['temp','name','random'])
df

temp      name  random
0     68   akshaya      10
1     82   akshaya      13
2     58      blue      13
3     45      pink      13
4     49      pink      14
5     12   akshaya      10
6     53   hemanka      11
7     78      blue      11
8     98      blue      11
9     30   hemanka      14
10    22      blue      12
11    37      blue      13
12    20   hemanka      13
13    20   akshaya      10
14    44      pink      13
15    72    shruti      13
16    53      blue      10
17    95   akshaya      14
18    49   hemanka      12
19    66      pink      12

In [42]:
df.head() # returns starting of the df

temp     name  random
0    68  akshaya      10
1    82  akshaya      13
2    58     blue      13
3    45     pink      13
4    49     pink      14

In [43]:
df.tail(3)

temp      name  random
17    95   akshaya      14
18    49   hemanka      12
19    66      pink      12

In [44]:
type(df)

pandas.core.frame.DataFrame

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int64
name      20 non-null object
random    20 non-null int64
dtypes: int64(2), object(1)
memory usage: 608.0+ bytes


In [49]:
df.size# returns size or the total number of elements i.e, rows and columns

60

In [50]:
df.shape # returns tuple shape (row,col)

(20, 3)

In [51]:
df.ndim   #returns dimensions. 1 for 1d(series), 2 for 2d(dataframes)

2

In [3]:
class1 = ['bird','bird','bird','bird','mammal','mammal','mammal','mammal']
max_speed= [389.0, 24.0, np.nan,25.6,80.5,np.nan,np.nan,75.5]
names = ['falcon','parrot','dove','sparrow','lion','monkey','cow','bat']
numbers=[30,26,10,45,70,1,90,5]


In [4]:
data={'names':names,'classification':class1,'maximum speed':max_speed,'numbers':numbers}
df=pd.DataFrame(data)
df

names classification  maximum speed  numbers
0   falcon           bird          389.0       30
1   parrot           bird           24.0       26
2     dove           bird            NaN       10
3  sparrow           bird           25.6       45
4     lion         mammal           80.5       70
5   monkey         mammal            NaN        1
6      cow         mammal            NaN       90
7      bat         mammal           75.5        5

In [5]:
df.set_index('numbers')

names classification  maximum speed
numbers                                       
30        falcon           bird          389.0
26        parrot           bird           24.0
10          dove           bird            NaN
45       sparrow           bird           25.6
70          lion         mammal           80.5
1         monkey         mammal            NaN
90           cow         mammal            NaN
5            bat         mammal           75.5

In [6]:
df.sort_index(axis=0,ascending=False)

names classification  maximum speed  numbers
7      bat         mammal           75.5        5
6      cow         mammal            NaN       90
5   monkey         mammal            NaN        1
4     lion         mammal           80.5       70
3  sparrow           bird           25.6       45
2     dove           bird            NaN       10
1   parrot           bird           24.0       26
0   falcon           bird          389.0       30

In [97]:
df.sort_index(axis=0,ascending=True)

names classification  maximum speed  numbers
0   falcon           bird          389.0       30
1   parrot           bird           24.0       26
2     dove           bird            NaN       10
3  sparrow           bird           25.6       45
4     lion         mammal           80.5       70
5   monkey         mammal            NaN        1
6      cow         mammal            NaN       90
7      bat         mammal           75.5        5

In [7]:
df.sort_values(by='numbers',ascending=False)

names classification  maximum speed  numbers
6      cow         mammal            NaN       90
4     lion         mammal           80.5       70
3  sparrow           bird           25.6       45
0   falcon           bird          389.0       30
1   parrot           bird           24.0       26
2     dove           bird            NaN       10
7      bat         mammal           75.5        5
5   monkey         mammal            NaN        1

In [8]:
df.isnull()

names  classification  maximum speed  numbers
0  False           False          False    False
1  False           False          False    False
2  False           False           True    False
3  False           False          False    False
4  False           False          False    False
5  False           False           True    False
6  False           False           True    False
7  False           False          False    False

In [9]:
df.notnull()

names  classification  maximum speed  numbers
0   True            True           True     True
1   True            True           True     True
2   True            True          False     True
3   True            True           True     True
4   True            True           True     True
5   True            True          False     True
6   True            True          False     True
7   True            True           True     True

In [10]:
df.dropna()

names classification  maximum speed  numbers
0   falcon           bird          389.0       30
1   parrot           bird           24.0       26
3  sparrow           bird           25.6       45
4     lion         mammal           80.5       70
7      bat         mammal           75.5        5

In [11]:
# iloc = index location
# loc = location - index or name

df.iloc[1:]

names classification  maximum speed  numbers
1   parrot           bird           24.0       26
2     dove           bird            NaN       10
3  sparrow           bird           25.6       45
4     lion         mammal           80.5       70
5   monkey         mammal            NaN        1
6      cow         mammal            NaN       90
7      bat         mammal           75.5        5

In [12]:
df.iloc[2:,2:]

maximum speed  numbers
2            NaN       10
3           25.6       45
4           80.5       70
5            NaN        1
6            NaN       90
7           75.5        5

In [13]:
df.iloc[2:5,1:5]

classification  maximum speed  numbers
2           bird            NaN       10
3           bird           25.6       45
4         mammal           80.5       70

In [14]:
df.loc[3,:]

names             sparrow
classification       bird
maximum speed        25.6
numbers                45
Name: 3, dtype: object

In [15]:
df.loc[[1,3,5,7],['names','maximum speed']]

names  maximum speed
1   parrot           24.0
3  sparrow           25.6
5   monkey            NaN
7      bat           75.5

In [16]:
df.loc[(df.numbers > 30)]

names classification  maximum speed  numbers
3  sparrow           bird           25.6       45
4     lion         mammal           80.5       70
6      cow         mammal            NaN       90

In [17]:
#merging and concatination

d1 = pd.DataFrame([['parrot', 1], ['sparrow', 2]],columns=['Birds', 'number'])
d2 = pd.DataFrame([['L', 3, 'lion'], ['T', 4, 'tiger']],columns=['letter', 'number', 'animal'])

In [18]:
d1

Birds  number
0   parrot       1
1  sparrow       2

In [19]:
d2

letter  number animal
0      L       3   lion
1      T       4  tiger

In [20]:
pd.concat([d1,d2],axis=0)

F:\ANACONDA\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Birds animal letter  number
0   parrot    NaN    NaN       1
1  sparrow    NaN    NaN       2
0      NaN   lion      L       3
1      NaN  tiger      T       4

In [21]:

pd.concat([d1,d2],axis=1)

Birds  number letter  number animal
0   parrot       1      L       3   lion
1  sparrow       2      T       4  tiger

In [22]:
df1=pd.DataFrame({'lkey':['foo','bee','cee','foo'],
                 'value':[1,2,3,4]})
df2=pd.DataFrame({'rkey':['foo','dee','bee','cee'],
                 'value':[5,6,7,8]})


In [23]:
df1

lkey  value
0  foo      1
1  bee      2
2  cee      3
3  foo      4

In [24]:
df2

rkey  value
0  foo      5
1  dee      6
2  bee      7
3  cee      8

In [25]:
df1.merge(df2,left_on='lkey',right_on='rkey')


lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        4  foo        5
2  bee        2  bee        7
3  cee        3  cee        8

In [26]:
df1.merge(df2,left_on='lkey',right_on='rkey', suffixes=('_left','_right'))

lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           4  foo            5
2  bee           2  bee            7
3  cee           3  cee            8